try {
  console.log("try블럭");
} catch (error) {
  console.log("catch 블럭");
  console.log("예외가 발생했습니다");
} finally {
  console.log("finally 블럭");
}
